In [1]:
import numpy as np

In [4]:
lst = list(range(1,30))
arr1=np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
arr2=np.arange(1,40)  
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [8]:
arr3=np.array([1,2,3,4,5,6,7,8,9,14,45])  #method to form an array
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 45])

In [15]:

arr4=np.zeros((10))
arr4
  #used to form a zero array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arr5= np.ones((10))  #used to create array of 1
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr6=np.zeros((5,10))   # 2d array formation of zeros
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr7= np.ones((5,10))  # 2d array formation of ones
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr8=np.linspace(1,10,8)  # 1 to 10 element work in range and by 20 we giving values to them
arr8

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [25]:
arr9 = np.arange(0,30).reshape(10,3)
arr9 # used to create 1d array into 2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [26]:
arr10=np.arange(0,100).reshape(10,10)
arr10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Random Numbers array gen

In [27]:
arr_1d=np.random.randint(1,5,9)  # give 1 to 5 same no. but after it gives random values but in range
arr_1d

array([2, 4, 3, 4, 1, 1, 3, 2, 3])

In [29]:
arr_2d=np.random.randint(1,5,(5,2))  #2d array of random creation
arr_2d

array([[1, 4],
       [3, 2],
       [1, 4],
       [4, 3],
       [3, 4]])

In [30]:
arr_3d= np.random.random(10)  # giving 10 random values
arr_3d

array([0.16142784, 0.76828394, 0.23109332, 0.08417875, 0.0265319 ,
       0.59896028, 0.98638442, 0.45143674, 0.42492752, 0.6335162 ])

In [32]:
arr_4d = np.random.random((5,10))      #  giving 2d random values
arr_4d

array([[0.96218147, 0.27820496, 0.856354  , 0.76045732, 0.07237377,
        0.40270879, 0.84621093, 0.93951926, 0.32462624, 0.51072498],
       [0.73642408, 0.51862932, 0.0322338 , 0.11038932, 0.0459811 ,
        0.16829953, 0.59165705, 0.63734734, 0.04937397, 0.77350454],
       [0.91727446, 0.6405046 , 0.81057452, 0.6616953 , 0.63858972,
        0.08600475, 0.7824553 , 0.45182619, 0.79005422, 0.26052846],
       [0.56167718, 0.5682571 , 0.65034934, 0.87048502, 0.83310177,
        0.59202348, 0.46803941, 0.47497549, 0.63782669, 0.52656688],
       [0.56643416, 0.39740587, 0.36754383, 0.09534996, 0.90838378,
        0.72430281, 0.6084862 , 0.99614873, 0.02968001, 0.40967816]])

# Array Attributes

In [35]:
arr=np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [36]:
arr.shape  # gives shapes of matrix

(12, 5)

In [37]:
arr.dtype   # know about the datatype 

dtype('int32')

In [38]:
arr.ndim  # we know about the type of array wheather it is 1d ,2d 3d.... 

2

In [39]:
arr.size   # gives info about the size

60

In [40]:
arr.flatten()    # convert any array into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()  # it is also use to convert into 1D
 

In [50]:
lst=[[1,3,4,5],[6,7,8,9]]    # making 2D array uing list
lst

[[1, 3, 4, 5], [6, 7, 8, 9]]

In [51]:
arr_454= np.array(lst)
arr_454

array([[1, 3, 4, 5],
       [6, 7, 8, 9]])

In [54]:
arr.shape

(2,)

In [56]:
arr.T.shape

(2,)