In [4]:
import numpy as np

In [5]:
lst = list(range(1,30))
arr1=np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr2=np.arange(1,40)  
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [7]:
arr3=np.array([1,2,3,4,5,6,7,8,9,14,45])  #method to form an array
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 45])

In [8]:

arr4=np.zeros((10))
arr4
  #used to form a zero array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr5= np.ones((10))  #used to create array of 1
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
arr6=np.zeros((5,10))   # 2d array formation of zeros
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr7= np.ones((5,10))  # 2d array formation of ones
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
arr8=np.linspace(1,10,8)  # 1 to 10 element gives in range and total element are 8
arr8

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [13]:
arr9 = np.arange(0,30).reshape(10,3)
arr9 # used to create 1d array into 2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [14]:
arr10=np.arange(0,100).reshape(10,10)
arr10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Random Numbers array gen

In [15]:
arr_1d=np.random.randint(1,5,9)  # give 1 to 5 same no. but after it gives random values but in range
arr_1d

array([4, 3, 1, 3, 1, 4, 3, 4, 2])

In [16]:
arr_2d=np.random.randint(1,5,(5,2))  #2d array of random creation
arr_2d

array([[2, 2],
       [1, 2],
       [2, 2],
       [2, 2],
       [4, 1]])

In [17]:
arr_3d= np.random.random(10)  # giving 10 random values
arr_3d

array([0.35019164, 0.06129293, 0.70288858, 0.58482708, 0.01507515,
       0.36521234, 0.66230596, 0.22308865, 0.4052943 , 0.50885327])

In [18]:
arr_4d = np.random.random((5,10))      #  giving 2d random values
arr_4d

array([[0.32767042, 0.9374809 , 0.19076836, 0.169663  , 0.69745951,
        0.650186  , 0.60138056, 0.96871128, 0.46306134, 0.13551951],
       [0.70144324, 0.87108867, 0.02237395, 0.57077004, 0.96113401,
        0.41653827, 0.30518753, 0.64676883, 0.29921133, 0.0245812 ],
       [0.46421189, 0.79605041, 0.06252833, 0.10209309, 0.22126362,
        0.06071756, 0.55393157, 0.63285451, 0.6266279 , 0.68914797],
       [0.86446055, 0.74812689, 0.21716939, 0.30458743, 0.01673492,
        0.67974665, 0.89303315, 0.87327839, 0.14048968, 0.98840489],
       [0.11864761, 0.45681037, 0.59227415, 0.30111962, 0.64552387,
        0.7432814 , 0.55906953, 0.28001144, 0.48673798, 0.06250295]])

# Array Attributes

In [19]:
arr=np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [20]:
arr.shape  # gives shapes of matrix

(12, 5)

In [21]:
arr.dtype   # know about the datatype 

dtype('int32')

In [22]:
arr.ndim  # we know about the type of array wheather it is 1d ,2d 3d.... 

2

In [23]:
arr.size   # gives info about the size

60

In [24]:
arr.flatten()    # convert any array into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
arr.ravel()  # it is also use to convert into 1D
 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
lst=[[1,3,4,5],[6,7,8,9]]    # making 2D array uing list
lst

[[1, 3, 4, 5], [6, 7, 8, 9]]

In [27]:
arr_454= np.array(lst)
arr_454

array([[1, 3, 4, 5],
       [6, 7, 8, 9]])

In [28]:
arr.shape

(12, 5)

In [29]:
arr.T.shape

(5, 12)

# Accessing elements from 1D and 2D array

* for 1D array[row_start:end:step/skip]
* for 2D array[row_start:end:step/skip/skip,column_start:skip/step]

In [30]:
arr= np.arange(0,60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
arr[38]

38

In [32]:
arr[0:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
arr= np.arange(0,60).reshape(12,5)    #formation of 2D array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [45]:
arr[7:8,4]

array([39])

In [39]:
arr[5]   #accessing single element in 2d

array([25, 26, 27, 28, 29])

In [40]:
arr[3,3]  # used to access single element  in 2D


18

In [41]:
arr[0:5,1:2]  # first take 0 to 5 column and then taking 1st column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [42]:
arr[1,3:5]

array([8, 9])

In [44]:
arr[7:8,4]

array([39])

In [48]:
arr[7:8,4][0]=100   # value replace
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [50]:
arr[11][-1]  # acccessing last element of 1D array

59

In [52]:
arr[-1][-1]  # acccessing last element of 1D array

59

In [53]:
arr[-1,-1]   # acccessing last element of 1D array

59

In [59]:
arr[11:,-1][0] # acccessing last element of 1D array

59

In [60]:
arr[11,4]     # acccessing last element of 1D array

59

# for 3D array

In [64]:
arr=np.array(np.arange(225).reshape(5,15,3))   # formtaion of 3D array  
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [65]:
arr.shape
# -----> table
# -----> rows
# -----> column

(5, 15, 3)

In [66]:
arr.size

225

In [67]:
arr.dtype

dtype('int32')